Feature/homework 9
MurzinaN/SWAGLABS_Murzina_Natasha pull request #2
Opened 2022-07-12 18:18 UTC by MurzinaN

2 pages: ShoppingCartPage, CheckoutYourInfoPage
3 tests in ShoppingCartTest
3 tests in CheckoutYourInfoTest
and checklist

2022-07-12 18:49 UTC, voropa requested changes

2022-07-12 18:49 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +public class CheckoutYourInfoPage extends HomePage{
Class name could be simplified to "CheckoutPage"

2022-07-12 18:49 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
**is**Missing?

2022-07-12 18:49 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +    public boolean productContainerShoppingCartMissing(String productName){
It's  better to use thк following naming for this kind of methods:
isBlablablaPresent()

2022-07-12 18:59 UTC, MurzinaN commented on src/test/java/pages/CheckoutYourInfoPage.java
> +public class CheckoutYourInfoPage extends HomePage{
там только то что касается Checkout: Your Infoformation, там дальше CHECKOUT: OVERVIEW, я решила, что это должно быть отдельно

2022-07-12 18:59 UTC, MurzinaN commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
у меня там проверки на отсутствие, что бы не выдавало исключение NoSuchElementException

2022-07-12 18:59 UTC, MurzinaN commented on src/test/java/pages/ShoppingCartPage.java
> +    public boolean productContainerShoppingCartMissing(String productName){
т.е. в любом случае называть ...Present() даже если элемент должен отсутствовать?

2022-07-12 19:43 UTC, voropa commented on src/test/java/pages/ShoppingCartPage.java
> +    public boolean productContainerShoppingCartMissing(String productName){
"элемент должен отсутствовать?" - звучит как требование или проверка из теста, а page-классы ничего не знают про тестовые сценарии и проверки, они должны предоставлять набор методов и действий с лементами на странице. 
Так что да, в общем случае обычно такие методы именуются is...Present(), а уже в тесте в зависимости от необходимой проверки вы используете результат этого метода.

2022-07-12 19:44 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
Просто переделайте возвращаемое значение в обратную сторону:
!isEmpty()

2022-07-12 19:45 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +public class CheckoutYourInfoPage extends HomePage{
Звучит логично, но у вас в коде нет CHECKOUT: OVERVIEW страницы, поэтому я и посоветовал переименовать имеющуюся

2022-07-12 20:01 UTC, MurzinaN commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
Если я в методе поменяю isEmpty на isDisplayed, при том что этого элемента не будет на дисплее, тест выдаст исключение, или я чего-то не понимаю?

2022-07-12 20:20 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
все верно, потому что isDisplayed() и isEmpty (isPresent) - это разные атрибуты и разные проверки, точнее метод isDisplayed возвращает значение  атрибута "displayed" у элемента, 
А в случае с isPresent() подойдет ваша логика с массивом элементов и проверкой на isEmpty()

2022-07-12 20:34 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
Пример:
на странице есть элемент с локатором
By element = By.id("elm")
В таком случае метод
public boolean isElementDisplayed() {
return driver.findElement(element).isDisplayed();
} - проверяет отображение элемента на странице,
а метод
public boolean isElementPresent() {
return !driver.findElements(element).isEmpty();
} - проверяет наличие элемента на странице

2022-07-12 20:40 UTC, MurzinaN commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
В общем,  я поменяла название методов и классов, в остальном гуд?

2022-07-12 20:49 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
В остальном все хорошо. Но с Present методами у вас все равно неправильно работает. 

Попробуйте вчитаться внимательно в название метода и в то, что он возвращает.
И посмотрите пример, который я описал выше

2022-07-12 21:03 UTC, MurzinaN commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
!driver.findElements.isEmpty возвращает true не на пустой список, а на то что элементы найдены, так? Просто мы пару занятий назад обсуждали,  как избежать исключения и вы про этот вариант не упамянули. Переделывать?

2022-07-12 22:32 UTC, voropa commented on src/test/java/pages/CheckoutYourInfoPage.java
> +    public boolean checkoutFormMissing(){
> !driver.findElements.isEmpty возвращает true не на пустой список, а на то что элементы найдены, так?
Именно
В таком случае метод isBlaBlaBlaPresent() будет возвращать true, если список не пустой и элемент найден, соответсвенно он present и false в обратном случае, когда элементы не present

2022-07-13 10:10 UTC, voropa approved these changes

2022-07-13 16:01 UTC, merged