Page Factory - LoginPage
MurzinaN/SWAGLABS_Murzina_Natasha pull request #3
Opened 2022-07-22 11:47 UTC by MurzinaN

Data Driven Test - LoginTest, ProductsTest, ItemDetailsTest, CheckoutTest
Не получается запустить в двух браузерах, если добавляю firefox, все тесты по два раза проходят в  firefox, а chrome игнорируется.

2022-07-22 13:07 UTC, voropa requested changes

2022-07-22 13:07 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    public boolean isLoginFormPresent() {
Получается, что у вас этот метод всегда возвращает true, внезависимости от того, что там на самом деле displayed.

2022-07-22 13:07 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +    @FindBy(className = "product_sort_container")
Не комбинируйте page object и page factor patterns в рамказ одного класса. Используйте что-то одно в одном классе-странице

2022-07-22 13:07 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +        List<WebElement> options = select.getOptions();
Используйте встроенные в Select клас методы для выбора опций: selectOptionByName/Index/value вместо option.click()

2022-07-22 13:07 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +    public List<String> expectedProductNamesSortNameZToA() {
Page-класс ничего не должен знать про тестовые данные, а тем более генерировать их. А expectedProductNames звучит как тестовые данные. Перенесите их в тесты

2022-07-22 13:07 UTC, voropa commented on src/test/java/tests/BaseTest.java
> +     /* @AfterClass(alwaysRun = true)
Почему закоментировали? Драйвер нужно закрывать после тестов

2022-07-22 13:07 UTC, voropa commented on smokeTest.xml
> +                <include name="smoke"/>
Получается у вас в smokeTest suite запускаются все виды тестов: negative,smoke и regression.
Задача в том, чтобы сделать 3 отдельных xml файла под каждую группу тестов

2022-07-22 13:37 UTC, MurzinaN commented on src/test/java/pages/LoginPage.java
> +    public boolean isLoginFormPresent() {
Почему? Ведь если время ожидание закончится, а элемент не появится выдаст исключение. Я когда запускаю все тесты вместе именно этот тест даже с ожиданием падает 2 раза из 5

2022-07-22 13:37 UTC, MurzinaN commented on src/test/java/pages/ProductsPage.java
> +    @FindBy(className = "product_sort_container")
я помню, просто вы говорили, что в наших кривых проектах можно попробовать, а так как раз очень удобный случай

2022-07-22 14:36 UTC, voropa commented on src/test/java/pages/LoginPage.java
> +    public boolean isLoginFormPresent() {
Нет, ну ожидание - это ожидание, а проверка атрибута isDisplayed() это другое действие, никак не связанное с ожиданием. Взависимости от того, что вам нужно в тесте, реализуйте соответсвующий метод: либо waitForLoginFormPresent(), в котором будет ожидание, либо isLoginFormPresent(), который будет возвращать значение атрибута isDisplayed в данный момент времени.

2022-07-22 14:37 UTC, voropa commented on src/test/java/pages/ProductsPage.java
> +    @FindBy(className = "product_sort_container")
Да, можно  попробовать использовать page object и page factory в разных классах, но не в одном, так лучше не делать - это уже антипаттерн получается

2022-07-22 14:41 UTC, voropa requested changes

2022-07-22 14:41 UTC, voropa commented on regressionTestFF.xml
> +<suite name="Smoke Tests" parallel="classes" thread-count="2">
Вероятно название должно быть Regression

2022-07-22 14:41 UTC, voropa commented on negativeTestFF.xml
> +<suite name="Smoke Tests" parallel="classes" thread-count="2">
а тут negative.
перепроверьте все названия. пожалуйста. 
И зачем вы создали 6 xml файлов? нужно всего 3 - по одному на кажддый набор тестов. А браузер мы поэтому и вынесли параметром в xml файле, чтобы не создавать отдельный xml под каждый браузер, а менять этот параметр, когда нужно запустить тесты на олпределенном браузере

2022-07-22 14:41 UTC, voropa commented on src/test/java/tests/ProductsTest.java
> +        Assert.assertEquals(ProductsPage.sortNameZToA().get(0), expectedProductNamesSortNameZToA().get(0));
Лучше сравнивать обе коллецции (массива) целиком, чем выборочно по элементам. 
assertEquals(arrayList1, arrayList2)

2022-07-22 15:14 UTC, MurzinaN commented on src/test/java/pages/LoginPage.java
> +    public boolean isLoginFormPresent() {
Мне нужен метод который проверяет наличие элемента, и, когда я запускаю его отдельно, он прекрасно отрабатывает без ожидания, а если запустить группу то именно этот тест через раз падает не дождавшись элемента, поэтому я добавила туда ожидание

2022-07-26 13:26 UTC, voropa approved these changes

2022-07-26 14:16 UTC, merged